/*
 Copyright (c) 2003-2021, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or https://ckeditor.com/legal/ckeditor-oss-license
*/
CKEDITOR.dialog.add("specialchar",function(f){var g,n=f.lang.specialchar,k,l,p,d,e,q;l=function(c){var a;c=c.data?c.data.getTarget():new CKEDITOR.dom.element(c);"a"==c.getName()&&(a=c.getChild(0).getHtml())&&(c.removeClass("cke_light_background"),g.hide(),"source"==f.mode?MyBBEditor.insertText(a,"",f.name+"_2"):(c=f.document.createElement("span"),c.setHtml(a),f.insertText(c.getText())))};p=CKEDITOR.tools.addFunction(l);e=function(c,a){var b;a=a||c.data.getTarget();"span"==a.getName()&&(a=a.getParent());
if("a"==a.getName()&&(b=a.getChild(0).getHtml())){k&&d(null,k);var e=g.getContentElement("info","htmlPreview").getElement();g.getContentElement("info","charPreview").getElement().setHtml(b);e.setHtml(CKEDITOR.tools.htmlEncode(b));a.getParent().addClass("cke_light_background");k=a}};d=function(c,a){a=a||c.data.getTarget();"span"==a.getName()&&(a=a.getParent());"a"==a.getName()&&(g.getContentElement("info","charPreview").getElement().setHtml("\x26nbsp;"),g.getContentElement("info","htmlPreview").getElement().setHtml("\x26nbsp;"),
a.getParent().removeClass("cke_light_background"),k=void 0)};q=CKEDITOR.tools.addFunction(function(c){c=new CKEDITOR.dom.event(c);var a=c.getTarget(),b;b=c.getKeystroke();var r="rtl"==f.lang.dir;switch(b){case 38:if(b=a.getParent().getParent().getPrevious())b=b.getChild([a.getParent().getIndex(),0]),b.focus(),d(null,a),e(null,b);c.preventDefault();break;case 40:(b=a.getParent().getParent().getNext())&&(b=b.getChild([a.getParent().getIndex(),0]))&&1==b.type&&(b.focus(),d(null,a),e(null,b));c.preventDefault();
break;case 32:l({data:c});c.preventDefault();break;case r?37:39:if(b=a.getParent().getNext())b=b.getChild(0),1==b.type?(b.focus(),d(null,a),e(null,b),c.preventDefault(!0)):d(null,a);else if(b=a.getParent().getParent().getNext())(b=b.getChild([0,0]))&&1==b.type?(b.focus(),d(null,a),e(null,b),c.preventDefault(!0)):d(null,a);break;case r?39:37:(b=a.getParent().getPrevious())?(b=b.getChild(0),b.focus(),d(null,a),e(null,b),c.preventDefault(!0)):(b=a.getParent().getParent().getPrevious())?(b=b.getLast().getChild(0),
b.focus(),d(null,a),e(null,b),c.preventDefault(!0)):d(null,a)}});return{title:n.title,minWidth:430,minHeight:280,buttons:[CKEDITOR.dialog.cancelButton],charColumns:17,onLoad:function(){for(var c=this.definition.charColumns,a=f.config.specialChars,b=CKEDITOR.tools.getNextId()+"_specialchar_table_label",d=['\x3ctable role\x3d"listbox" aria-labelledby\x3d"'+b+'" style\x3d"width: 320px; height: 100%; border-collapse: separate;" align\x3d"center" cellspacing\x3d"2" cellpadding\x3d"2" border\x3d"0"\x3e'],
e=0,g=a.length,h,m;e<g;){d.push('\x3ctr role\x3d"presentation"\x3e');for(var k=0;k<c;k++,e++)if(h=a[e]){h instanceof Array?(m=h[1],h=h[0]):(m=h.replace("\x26","").replace(";","").replace("#",""),m=n[m]||h);var l="cke_specialchar_label_"+e+"_"+CKEDITOR.tools.getNextNumber();d.push('\x3ctd class\x3d"cke_dark_background" style\x3d"cursor: default" role\x3d"presentation"\x3e\x3ca href\x3d"javascript: void(0);" role\x3d"option" aria-posinset\x3d"'+(e+1)+'"',' aria-setsize\x3d"'+g+'"',' aria-labelledby\x3d"'+
l+'"',' class\x3d"cke_specialchar" title\x3d"',CKEDITOR.tools.htmlEncode(m),'" onkeydown\x3d"CKEDITOR.tools.callFunction( '+q+', event, this )" onclick\x3d"CKEDITOR.tools.callFunction('+p+', this); return false;" tabindex\x3d"-1"\x3e\x3cspan style\x3d"margin: 0 auto;cursor: inherit"\x3e'+h+'\x3c/span\x3e\x3cspan class\x3d"cke_voice_label" id\x3d"'+l+'"\x3e'+m+"\x3c/span\x3e\x3c/a\x3e\x3c/td\x3e")}d.push("\x3c/tr\x3e")}d.push("\x3c/tbody\x3e\x3c/table\x3e",'\x3cspan id\x3d"'+b+'" class\x3d"cke_voice_label"\x3e'+
n.options+"\x3c/span\x3e");this.getContentElement("info","charContainer").getElement().setHtml(d.join(""))},contents:[{id:"info",label:f.lang.common.generalTab,title:f.lang.common.generalTab,padding:0,align:"top",elements:[{type:"hbox",align:"top",widths:["320px","90px"],children:[{type:"html",id:"charContainer",html:"",onMouseover:e,onMouseout:d,focus:function(){var c=this.getElement().getElementsByTag("a").getItem(0);setTimeout(function(){c.focus();e(null,c)},0)},onShow:function(){var c=this.getElement().getChild([0,
0,0,0,0]);setTimeout(function(){c.focus();e(null,c)},0)},onLoad:function(c){g=c.sender}},{type:"hbox",align:"top",widths:["100%"],children:[{type:"vbox",align:"top",children:[{type:"html",html:"\x3cdiv\x3e\x3c/div\x3e"},{type:"html",id:"charPreview",className:"cke_dark_background",style:"border:1px solid #eeeeee;font-size:28px;height:40px;width:70px;padding-top:9px;font-family:'Microsoft Sans Serif',Arial,Helvetica,Verdana;text-align:center;",html:"\x3cdiv\x3e\x26nbsp;\x3c/div\x3e"},{type:"html",
id:"htmlPreview",className:"cke_dark_background",style:"border:1px solid #eeeeee;font-size:14px;height:20px;width:70px;padding-top:2px;font-family:'Microsoft Sans Serif',Arial,Helvetica,Verdana;text-align:center;",html:"\x3cdiv\x3e\x26nbsp;\x3c/div\x3e"}]}]}]}]}]}});